config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :todos do 
    collection do
      patch :sort
    end
    member do 
      patch :mark_as_done
    end
  end
  resources :todo_types

end

app/controllers/todo_types_controller.rb
class TodoTypesController < ApplicationController
  before_action :set_todo_type, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!

  def index
    @todo_types = TodoType.all
  end

  def show;end

  def new
    @todo_type = TodoType.new
  end

  def edit;end

  def create
    @todo_type = TodoType.new(todo_type_params)

    respond_to do |format|
      if @todo_type.save
        format.html { redirect_to @todo_type, notice: 'Todo type was successfully created.' }
        format.json { render :show, status: :created, location: @todo_type }
      else
        format.html { render :new }
        format.json { render json: @todo_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo_type.update(todo_type_params)
        format.html { redirect_to @todo_type, notice: 'Todo type was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo_type }
      else
        format.html { render :edit }
        format.json { render json: @todo_type.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo_type.destroy
    respond_to do |format|
      format.html { redirect_to todo_types_url, notice: 'Todo type was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_todo_type
      @todo_type = TodoType.find(params[:id])
    end

    def todo_type_params
      params.require(:todo_type).permit(:name)
    end
end

app/views/todo_types/_form.html.erb
<%= form_with(model: todo_type, local: true) do |form| %>
  <%= render "partials/form_errors", object: todo_type %>
  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, class: "form-control rounded-0" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary rounded-0" %>
    <%= link_to 'Back', todo_types_path, class: "btn btn-outline-primary rounded-0" %>
  </div>
<% end %>

app/views/todo_types/edit.html.erb
<h1>Editing Todo Type</h1>

<%= render 'form', todo_type: @todo_type %>

<%= link_to 'Show', @todo_type %> |
<%= link_to 'Back', todo_types_path %>

app/views/todo_types/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <h1>Todo Types</h1>
      <table class="table table-bordered">
        <thead>
          <tr>
            <th>Name</th>
            <th>Actions</th>
          </tr>
        </thead>

        <tbody>
          <% @todo_types.each do |todo_type| %>
            <tr>
              <td><%= todo_type.name %></td>
              <td>
                <%= link_to 'Show', todo_type, class: "btn btn-primary rounded-0" %>
                <%= link_to 'Edit', edit_todo_type_path(todo_type), class: "btn btn-secondary rounded-0" %>
                <%= link_to 'Destroy', todo_type, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger rounded-0" %>    
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New Todo Type', new_todo_type_path %>
    </div>
  </div>
</div>

app/views/todo_types/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card shadow rounded-0">
        <div class="card-body">
          <h1>New Todo type</h1>
          <%= render 'form', todo_type: @todo_type %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todo_types/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @todo_type.name %>
</p>

<%= link_to 'Edit', edit_todo_type_path(@todo_type) %> |
<%= link_to 'Back', todo_types_path %>