config/routes.rb
Rails.application.routes.draw do
  
  root "home#index"

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  
  resources :todos do 
    collection do
      patch :sort
    end
    member do 
      patch :mark_as_done
    end
  end
  resources :todo_types

end

app/models/todo.rb
class Todo < ApplicationRecord
  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :todo_type, optional: true
  belongs_to :user, optional: true
  validates :title, presence: true

  before_create :default_status

  def done?
    self.status == 'done'
  end

  def status_badge
    self.done? ? "success" : "danger"
  end

  private 

    def default_status
      self.status = 'pending'
    end

end

app/models/todo_type.rb
class TodoType < ApplicationRecord
  has_many :todos
  validates :name, presence: true, uniqueness: true
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: [:show, :edit, :update, :destroy, :mark_as_done]
  before_action :authenticate_user!
  skip_before_action :verify_authenticity_token, only: [:sort]

  def index
    @todos = current_user.todos.order('priority ASC')
  end

  def show;end

  def new
    @todo = Todo.new
  end

  def edit;end

  def create
    @todo = current_user.todos.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to @todo, notice: 'Todo was successfully created.' }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to @todo, notice: 'Todo was successfully updated.' }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @todo.destroy
    respond_to do |format|
      format.html { redirect_to todos_url, notice: 'Todo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def sort
    params[:todo].each_with_index do |id, index|
      current_user.todos.where(id: id).update_all(priority: index + 1)
    end
    head :ok
  end

  def mark_as_done
    @todo.update(status: 'done')
    respond_to do |format|
      format.js
    end
  end

  private
    def set_todo
      @todo = Todo.friendly.find(params[:id])
    end

    def todo_params
      params.require(:todo).permit!
    end
end

app/views/todos/_form.html.erb
<%= form_with(model: todo, local: true) do |form| %>
  <%= render "partials/form_errors", object: todo %>
  <div class="form-group">
    <%= form.label :todo_type_id %>
    <%= form.select :todo_type_id, options_for_select(todo_type_list, selected: todo.todo_type_id), {prompt: "Select type of Todo"}, {class: "form-control rounded-0"} %>
  </div>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: "form-control rounded-0" %>
  </div>

  <div class="form-group">
    <%= form.label :due_date %>
    <%= form.text_field :due_date, class: "form-control rounded-0" %>
  </div>

  <div class="actions">
    <%= form.submit class: "btn btn-primary rounded-0" %>
    <%= link_to 'Back', todos_path, class: "btn btn-outline-primary rounded-0" %>
  </div>
<% end %>

app/views/todos/_mark_as_done.html.erb
<p>
  <strong>Title:</strong>
  <%= todo.title %>
</p>
<p>
  <strong>Due date:</strong>
  <%= todo.due_date %>
</p>
<p>
  <strong>Status:</strong>
  <span class="badge badge-<%= todo.status_badge %>"><%= todo.status.capitalize %></span>
</p>
<p>
  <strong>Todo type:</strong>
  <%= @todo.todo_type.try(:name) %>
</p>
<%= link_to 'Edit', edit_todo_path(todo), class: "btn btn-secondary rounded-0" %> 
<%= link_to 'Delete', todo_path(todo), class: "btn btn-danger rounded-0", method: :delete, data: {confirm: "Are you sure?"} %> 
<%= link_to 'Back', todos_path, class: "btn btn-outline-primary rounded-0" %>  

app/views/todos/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card shadow rounded-0">
        <div class="card-body">
          <h1>Editing Todo</h1>
          <%= render 'form', todo: @todo %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todos/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card shadow rounded-0 mb-3 mt-4">
        <div class="card-body">
          <h1>Listing Todos</h1>
          <p class="lead">Manage your todo's order according to your choice. Just drag and drop them into any preferred order you want.</p>
        </div>
      </div>
      <div id="todo_list" class="list-group" data-url="<%= sort_todos_path %>">
        <% @todos.each do |todo| %>
          <%= link_to todo.title, todo, class: "list-group-item list-group-item-action mt-1", id: dom_id(todo) %>
        <% end %>
      </div>
      <div class="mt-5 mb-4">
        <%= link_to 'New Todo', new_todo_path, class: "btn btn-primary rounded-0" %>
      </div>
    </div>
  </div>
</div>

app/views/todos/mark_as_done.js.erb
$("#todo_detail").html("<%= escape_javascript render(partial: 'mark_as_done', locals: { todo: @todo } )%>");

app/views/todos/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-12">
      <div class="card shadow rounded-0">
        <div class="card-body">
          <h1>New Todo</h1>
          <%= render 'form', todo: @todo %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/todos/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 mt-5">
      <div class="row">
        <div class="col-md-6">
          <div class="card shadow rounded-0">
            <div class="card-body">
              <div id="todo_detail">
                <p>
                  <strong>Title:</strong>
                  <%= @todo.title %>
                </p>
                <p>
                  <strong>Due date:</strong>
                  <%= @todo.due_date %>
                </p>
                <p>
                  <strong>Status:</strong>
                  <span class="badge badge-<%= @todo.status_badge %>"><%= @todo.status.capitalize %></span>
                </p>
                <p>
                  <strong>Todo type:</strong>
                  <%= @todo.todo_type.try(:name) %>
                </p>
                <%= link_to 'Edit', edit_todo_path(@todo), class: "btn btn-secondary rounded-0" %> 
                <%= link_to 'Delete', todo_path(@todo), class: "btn btn-danger rounded-0", method: :delete, data: {confirm: "Are you sure?"} %> 
                <%= link_to 'Back', todos_path, class: "btn btn-outline-primary rounded-0" %>  
                <% unless @todo.done? %>
                  <%= link_to "Mark As Done", mark_as_done_todo_path(@todo), class: "btn btn-success rounded-0 shadow", method: :patch, remote: true %>
                <% end %>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>